############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
#  path: /app-test  #http://localhost:8088/app-test 可访问到项目
  port: 8088     # http://localhost:8088/接口即可访问到项目
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
############################################################
#
# 配置数据源信息
#
############################################################
spring:
  profiles:
    active: prod                                          #选择的环境（挂件）
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP（效率极高）
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
#    当前主配置文件就不配置了，不同环境自己配置
#    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#    username: root
#    password: luotao19950720
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数（5和10都可）
      maximum-pool-size: 20           # 最大连接数（hikariCP默认为10,无最小，服务器4核为10，八核及以上设为20）
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1 # 测试的连接语句
  servlet:
      multipart:
        max-file-size: 512000     # 文件上传大小限制为500kb
        max-request-size: 512000  # 请求大小限制为500kb

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.luotao.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件(classpath指的是resources文件夹)

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台输出日志（主要是SQL），dev环境需要。prod不需要（会占服务器硬盘）
############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.luotao.my.mapper.MyMapper
  not-empty: false     # 在进行数据库操作的时候，判断表达式 username！=null 时是否追加 username！=""
  identity: MYSQL       #数据库方言

# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true